# Generated by Django 5.2.6 on 2025-09-17 05:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('thumbnail', models.URLField()),
                ('category', models.CharField(choices=[('apparel', 'Apparel'), ('footwear', 'Footwear'), ('gear', 'Gear'), ('accessories', 'Accessories'), ('equipment', 'Equipment'), ('merch', 'Merch'), ('tools', 'Tools')])),
                ('is_featured', models.BooleanField()),
                ('rating', models.FloatField(default=5)),
                ('stock', models.IntegerField(default=100)),
            ],
        ),
    ]
