# Generated by Django 5.2.6 on 2025-09-17 03:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(default=uuid.UUID('bb8a6ad9-96d1-45c4-86ee-9d4c8ac3faeb'), primary_key=True, serialize=False),
        ),
    ]
