# Generated by Django 5.2.6 on 2025-09-17 03:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2f448727-d793-48a3-abfd-d7383255c791'), editable=False, primary_key=True, serialize=False),
        ),
    ]
